<?php

namespace AppBundle\Repository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends \Doctrine\ORM\EntityRepository
{
	//la méthode personnalisé listing admet un argument $age dont la valeur
	//par defaut est 100
	//la valeur de cet argument est ensuite utilisé dans la requête DQL
	public function listing($age = 100)
	{
		//Requete SQL avec filtre
        //Requête DQL (Doctrine Query Langage, très proche
        // du language SQL)    
        return $this
        	->getEntityManager()
        	->createQuery('
            SELECT p
            FROM AppBundle:Player p
            WHERE p.age < :age
            ORDER BY p.nom ASC')
            ->setParameter('age', $age)
            ->getResult();
	}
}
